### PR TITLE
Pushing new functionalities

### PR DESCRIPTION
**Pull request by clinique**
Hello Mathieu,
I based a work I've done for another project (openHab) on your Freeboxos library. I started to extend it a bit. Feel free to check.

Regards
Gaël

### CODE REVIEW

**Comment by MatMaul** [comment]
Hi Gaël,

Sorry for the late response, I fully missed the notification...
I am merging this right away.

What do you and @lolodomo think about relicensing to EPL ? I didn't know at the time that EPL as a redistribution clause, and openHAB is on EPL so...

**Comment by clinique** [comment]
Hi Mathieu,

Thanks for this merge, I'll inform @lolodomo that you're there. On my side, no problem to change licensing mode - on top, if it's align with openHAB, it's even better.

**Comment by lolodomo** [comment]
Hi Mathieu and Gael.

We can speak in French ?

Est-ce que le merge réalisé intégre bien toutes mes modifications transmises à Gael  ?  A priori oui

Si jamais je devais apporter de nouvelles modifications, dois-je les adresser à Mathieu.

Est-ce que la version de Mathieu est 100 % compatible avec le binding 1.7 de openHAB  ?

**Comment by clinique** [comment]
Hello @lolodomo ,
Oui, Mathieu a mergé ma dernière PR qui contenait tes modifs.
Je pense que pour les modifications ultérieures, il vaut mieux recentraliser sur le git d'origine, à savoir celui de Mathieu.

**Comment by MatMaul** [comment]
Yes please send the pull request on my repo, now that I know that at least one project is using it I will look more often to it. Everything have been merged.
@lolodomo can you confirm (in English for this time please) that you agree to the EPL re licensing ? I prefer to have a written and explicit acknowledge of this kind of tricky stuff.
After that we can switch to french I don't care :)

**Comment by lolodomo** [comment]
Is English language a requirement in Git hub ?

I am not an expert in Open Source licenses but I agree with a re-licensing of the code to EPL. My understanding is that we will be 100% ok with usage in openHAB which uses the EPL license too.

I am curious to know if "linking" a Java library using GPL license to a software using EPL license is legal or not ?

@Mathieu: can you tell us in which context you use this library ?

**Comment by MatMaul** [comment]
Regarding English I don't really know, I was asking because I prefer to handle legal stuff like relicensing in English.
What do you think about dual licensing EPL/LGPL2.1+ ? Unfortunately I just remembered that EPL and GPLs licenses are fully incompatible, so this lib could not be used by GPL softwares if only released on EPL.
Regarding my use of it : I wrote a backend plugin for https://github.com/syncany/syncany
At the time the plugins were still in the main repo and I was reluctant to publish it because it had a dependency to my lib which is not in maven, I should (rewrote and ?) publish it now that plugins are in separate projects.

**Comment by lolodomo** [comment]
@MatMaul  :  could you  finally apply the change to move the code to a dual license EPL + LGPL please  ? 
You can take a look at project jgrapht for example.
@clinique for information

**Comment by MatMaul** [comment]
Ok let's make the license change now.

**Pull request merged**
